OMBCONNECT OWB_RTOWNER/INFORM@10.40.200.166:12235:DWIO

set pack [lindex $argv 0]
set pack [string toupper $pack]

OMBCC 'INFORM'
OMBCONNECT CONTROL_CENTER
OMBCOMMIT
OMBCC 'PFM_INFORM'
OMBCREATE TRANSIENT DEPLOYMENT_ACTION_PLAN 'RAL_PF'
OMBALTER DEPLOYMENT_ACTION_PLAN 'RAL_PF' ADD ACTION 'RAL_PF_MAIN' SET PROPERTIES(OPERATION) VALUES('REPLACE') SET REF PROCESS_FLOW_PACKAGE '$pack'
OMBDEPLOY DEPLOYMENT_ACTION_PLAN 'RAL_PF'
OMBDROP DEPLOYMENT_ACTION_PLAN 'RAL_PF'
OMBCOMMIT
OMBDISCONNECT 
