OMBCONNECT OWB_RTOWNER/<pass>@10.40.200.166:12235:DWIO

OMBCC 'INFORM'
OMBCONNECT CONTROL_CENTER
OMBCOMMIT
OMBCC 'PFM_INFORM'
OMBCREATE TRANSIENT DEPLOYMENT_ACTION_PLAN 'RAL_PF'
OMBALTER DEPLOYMENT_ACTION_PLAN 'RAL_PF' ADD ACTION 'RAL_PF_MAIN' SET PROPERTIES(OPERATION) VALUES('REPLACE') SET REF PROCESS_FLOW_PACKAGE 'PFP_DMTG'
OMBDEPLOY DEPLOYMENT_ACTION_PLAN 'RAL_PF'
OMBDROP DEPLOYMENT_ACTION_PLAN 'RAL_PF'
OMBVALIDATE "PROCESS_FLOW_PACKAGE" 'PFP_DMTG' OUTPUT VALIDATION_RESULT TO FILE ?C:/Scritps/PFP_DMTG.log? WRITE ALL

head C:/Scritps/PFP_DMTG.log

OMBCOMMIT
OMBDISCONNECT 