SELECT 
A.COLLECTION_ID, A.COLLECTION_NAME, A.COLLECTION_REFERENCE_ID, 
   A.COLLECTION_REFERENCE_TYPE, A.SCRIPTING_TYPE, A.COLLECTION_REFERENCE_NAME, 
   A.BUSINESS_NAME, A.DESCRIPTION, A.GENERATED, 
   A.IS_VALID, A.UPDATED_ON, A.CREATED_ON, 
   A.UPDATED_BY, A.CREATED_BY
FROM OWB_RTOWNER.ALL_IV_COLLECTION_REFERENCES A
where COLLECTION_REFERENCE_NAME = 'M_DFT_RAADKAMERZAKEN_1I_009';
;